# Generated by Django 4.2.6 on 2023-10-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_tag_rename_customer_customers_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
