# Generated by Django 4.2.6 on 2023-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pofile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
